### ISSUE TITLE
R4.1以下是否可支持

### ISSUE THREAD

**Issue by swcyo** [YuLab-SMU/MicrobiomeProfiler#1]
第一个Fork，结果我R的版本是4.0.3

直接提示：程序包'MicrobiomeProfiler'要求版本为>= 4.1.0的R

**Comment by zwbao** [comment]
> 第一个Fork，结果我R的版本是4.0.3
> 
> 直接提示：程序包'MicrobiomeProfiler'要求版本为>= 4.1.0的R

改一下 DESCRIPTION 里面的版本即可
