### ISSUE TITLE
使用默认Example的基因列表做富集时报错：Warning: Error in enricher_internal: no slot of name "keytype" for this object of class "GSON"

### ISSUE THREAD

**Issue by zzy221127** [YuLab-SMU/MicrobiomeProfiler#4]
您好，我尝试测试MicrobiomeProfiler的包，当按要求安装完后，按提示的example输入基因，发现报如下错误，然后网页一直卡着不动，请问要如何解决？非常想试用，期待您的回复！

> library(MicrobiomeProfiler)
> run_MicrobiomeProfiler()
载入需要的程辑包：shiny
Warning: 程辑包‘shiny’是用R版本4.2.2 来建造的

Gene Enrichment 页面报如下错误（使用example数据）：
Listening on http://127.0.0.1:5027
Warning: Error in enricher_internal: no slot of name "keytype" for this object of class "GSON"
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>

Microbe-Disease enrichment analysis 和Metabo-Pathway analysis页面（使用example数据） 报如下错误：
> run_MicrobiomeProfiler()
Listening on http://127.0.0.1:5027
Warning: Error in <Anonymous>: 不可以在类别为“enrichResult”的对象里的@‘keytype’槽指定类别为“NULL”的对象；is(value, "character")的值不是TRUE
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>

**Comment by mjchen1996** [comment]
应该是缺少gson包。
if(!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")
devtools::install_github("YuLab-SMU/gson")

**Comment by mjchen1996** [comment]
> 

Hi, 
I already fixed the issue with GSON data. Please try the newest version of MicrobiomeProfiler.

**Comment by mjchen1996** [comment]
Hi, all
I already fixed the issue with GSON data. Please try the newest version of MicrobiomeProfiler.
